USE [master]
GO
CREATE LOGIN [Admin] WITH PASSWORD=N'Admin123', DEFAULT_DATABASE=[CancherosDB], CHECK_EXPIRATION=OFF,
CHECK_POLICY=OFF
GO

USE [CancherosDB]
GO
CREATE USER [Admin] FOR LOGIN [Admin]
GO
USE [CancherosDB]
GO
ALTER ROLE [db_owner] ADD MEMBER [Admin]
GO